# Generated by Django 5.2.10 on 2026-03-16 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommended_pqc",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "deployed_cat",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "cat_justification",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "feasibility",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "migration_priority",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("overall", models.CharField(blank=True, default="", max_length=32)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "table_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_feedback",
                        to="core.tablerow",
                    ),
                ),
            ],
        ),
    ]
