# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_expertfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertfeedback",
            name="recommended_pqc_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expertfeedback",
            name="deployed_cat_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expertfeedback",
            name="cat_justification_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expertfeedback",
            name="feasibility_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expertfeedback",
            name="migration_priority_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expertfeedback",
            name="overall_why",
            field=models.TextField(blank=True, default=""),
        ),
    ]
